SERVER_PORT: 8080
CONTEXT_PATH: /api

############# DATABASE INFO ##################
DATABASE_URL: localhost
DATABASE_PASSWORD: chaimaa123
DATABASE_USERNAME: chaimaa
DATABASE_NAME: facturation
DATABASE_PORT: 5432