SERVER_PORT: 9090
CONTEXT_PATH: /api

############# DATABASE INFO ##################
DATABASE_URL: localhost
DATABASE_PASSWORD: 123
DATABASE_USERNAME: postgres
DATABASE_NAME: facturation
DATABASE_PORT: 5432